apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  type: ClusterIP
  ports:
    - name: cassandra-port
      port: 9042
      targetPort: 9042
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless
  labels:
    app: cassandra
spec:
  clusterIP: None
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
    - port: 7000
      targetPort: 7000
    - port: 7001
      targetPort: 70001
    - port: 7199
      targetPort: 7199
