steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/playground-s-11-a8d93435/syr-reg/myapp:v1', '.']
images:
  - 'europe-west1-docker.pkg.dev/playground-s-11-a8d93435/syr-reg/myapp:v1'