apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: europe-west1-docker.pkg.dev/playground-s-11-a8d93435/syr-reg/myapp@sha256:c7b7fc515c6fe9834fb799802793d3980b012229b9e1daa5c9d973782ca32843
        ports:
        - containerPort: 8888
