apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-prod
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: europe-west1-docker.pkg.dev/playground-s-11-a8d93435/syr-reg/myapp:v1
        ports:
        - containerPort: 8888
